"use client";

import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Pessoas from "./pessoas";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {   

  return (
    <>
      <Head>
        <title>Cadastro de pessoas e contatos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
          {/* <CardPessoas  /> */}
          <h1 className={ styles.tituloGeralCentro} >Pessoas e contatos</h1>
          <Pessoas/>

      </main>
    </>
  );
}
